# 1차원 배열에서 특정 수 index 뽑아내기
> numpy array 1차원 배열에서 특정한 수의 index를 뽑을 때 사용하는 함수

In [5]:
# 라이브러리 불러오기
import numpy as np

# 배열 만들기
sample_li = np.array([2, 3, 4, 5, 6])

# 4의 index 뽑기 
idx_4 = sample_li.index(4)
idx_4

AttributeError: 'numpy.ndarray' object has no attribute 'index'

list 자료형에서는 index 함수를 사용하여 item의 index를 뽑아낼 수 있었다. 하지만 numpy 배열에서는 위처럼 index 함수를 적용할 수 없다는 것을 알 수 있다. 때문에 numpy 배열에서는 np.where를 사용해야 한다.

In [6]:
# 4의 index 뽑기 
idx_4 = np.where(sample_li==4) # 값이 4인 item의 index의 위치를 알려준다.
idx_4

(array([2], dtype=int64),)

기대했던 것처럼 index 숫자만 간결히 나와주진 않지만, 원하는 수의 index를 뽑을 수 있다. 다른 예시를 하나 더 들어보자.

In [10]:
# 배열 만들기
sample_li2 = np.array(range(1000))
sample_li2

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

규칙성이 있으면 추측하기 쉬울 수 있으니 random 함수로 배열을 다시 생성해보겠습니다.

In [18]:
import random

sample_li2 = list(range(1000)) # 리스트 생성
sample_li2 = random.sample(sample_li2, 500) # 1000개의 숫자 중 무작위로 500개 추출해 리스트로 만듦
sample_li2 = np.array(sample_li2) # numpy array로 변환
sample_li2

array([665, 688, 253, 220, 510, 562, 167, 978, 610, 574, 668, 421, 446,
       752, 897, 455, 134, 332, 867, 330, 850, 488, 806, 667, 718, 703,
       305, 285,  71, 716,  58, 389, 772, 809, 876, 169, 458, 627, 483,
       586, 519,  25, 652, 342, 675, 432, 246, 465,  60, 906, 307, 662,
       367, 855, 274, 555, 295, 988, 576, 312, 400, 961, 890,  31, 621,
       683, 336, 243, 666, 880, 306,  70, 359, 221, 781, 569, 254, 840,
       757, 535, 938, 595, 697, 810, 538, 713, 525, 213, 471, 699, 460,
       543, 684, 425, 962, 717, 664, 453, 987, 986, 379, 748, 826,  24,
       913, 820, 883, 857, 528,  48, 411, 694, 164, 829, 710, 663, 396,
       141, 403,  73, 853, 153, 740, 247, 249, 537, 689, 758, 147, 154,
       145, 951, 765, 412, 601, 944, 395, 355, 715, 732, 286, 392, 542,
       578, 441, 172, 660, 341, 366, 303, 579, 302, 658, 828, 907, 722,
       452, 534, 597, 620, 289, 770, 191, 759, 943, 889, 346, 690, 202,
       707,  19, 695, 657,  63, 568, 138, 581,  17, 387, 497, 41

이 중 999의 index를 뽑아보자.

In [20]:
idx = np.where(sample_li2==999)
idx

(array([318], dtype=int64),)